eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.4:8761/eureka/
      #defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry
